### ISSUE TITLE
Package addon for Firefox

### ISSUE THREAD

**Issue by nukeador** [d4t4x/data-selfie#1]
Firefox also supports webextensions, it would be great if you can also package for it:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_Google_Chrome_extension

It feel weird that this extension is only available for Chrome and not a more privacy aware browser ;-)

**Comment by 01fade** [comment]
Yes, we do realize that Chrome is not associated with data privacy, but it is the most used browser, so it made sense for us to address those users first, to get it to as many people as possible. And one could make the argument, that especially Google Chrome users need this education and experience badly.

We are definitely thinking about porting it to Firefox (high on our priorities)! Right now, we have to figure out next steps for the current version first before we can expand. APIs cost money and finding funding is hard.

**Comment by mautematico** [comment]
I am not sure, but I think porting to Firefox can be very straightforward,
since, as noted by nukeador, Firefox does support webextensions, too.

Also I think a lot of mozillians would be interested on promoting the addon
to be used on Firefox (in fact, we both came here by a post made by a
mozillian).

About API cost and sponsors, unfortunately I have little to nothing to say.
Would you be willing to share with us info about the costs involved on the
development and maintenance of this add-on and the apis it's using?

**Comment by 01fade** [comment]
I have to admit, I haven't looked into porting to Firefox at all. I am going to do that asap! If it's easy of course we want to make it happen!

Yes, I believe so, too. It has been the most popular question.

About the costs, sure I can be transparent about that. I should have added links to the APIs we are using to the readme, but it's in our FAQs (dataselfie.it/faq). It's IBM Watson and Apply Magic Sauce from the University of Cambridge. Up until yesterday, the costs were approx. 1000 dollars per month. We were expecting - as absolute maximum - 10k users, but really only calculated costs for 5k. With the increase in users (as of today 20k+) the costs are about to double or even more. We have not taken any compensation for working on this.

**Comment by jonathangreco** [comment]
+1 for that

**Comment by 01fade** [comment]
Keep upvoting! It's on our to do list!
