### ISSUE TITLE
My profile is set to male but data selfie reports that I'm female ;-)

### ISSUE THREAD

**Issue by dogweather** [d4t4x/data-selfie#19]
I haven't looked into the code yet to see how it came up with that. I think it's still an interesting piece of data, even if it's "incorrect". I.e., my Facebook use most closely resembles a female's?

**Comment by 01fade** [comment]
Yes, it's normal to get a inaccurate predictions. Even Facebook itself probably can't everything right - just yet. But that's also not the point of the project, it's just to show the possibilities. You can read up in the FAQ (dataselfie.it/faq) about the API that is used here to determine the gender. In short the ids of the pages in your newsfeed are sent to the API (without any information about the user).

Closing because it's not really an issue.
